In [4]:
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset

In [33]:
dataset = load_dataset("lukebarousse/data_jobs")
df = dataset['train'].to_pandas()

In [34]:
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [18]:
df.loc[0:10, 'salary_rate':'salary_hour_avg']

   salary_rate  salary_year_avg  salary_hour_avg
0          NaN              NaN              NaN
1          NaN              NaN              NaN
2          NaN              NaN              NaN
3          NaN              NaN              NaN
4          NaN              NaN              NaN
5          NaN              NaN              NaN
6          NaN              NaN              NaN
7          NaN              NaN              NaN
8          NaN              NaN              NaN
9          NaN              NaN              NaN
10         NaN              NaN              NaN

In [35]:
median_salary_year = df['salary_year_avg'].median()
median_salary_hour = df['salary_hour_avg'].median()

In [36]:
df_filled = df
df_filled['salary_year_avg'] = df_filled['salary_year_avg'].fillna(median_salary_year)
df_filled['salary_hour_avg'] = df_filled['salary_hour_avg'].fillna(median_salary_hour)

In [41]:
df_filled.iloc[:10][['salary_year_avg', 'salary_hour_avg']]

   salary_year_avg  salary_hour_avg
0         115000.0            45.98
1         115000.0            45.98
2         115000.0            45.98
3         115000.0            45.98
4         115000.0            45.98
5         115000.0            45.98
6         115000.0            45.98
7         115000.0            45.98
8         115000.0            45.98
9         115000.0            45.98

In [37]:
df_filled = df_filled.drop_duplicates()
print(f"Original number of rows: {len(df)}")
print(f"Number of rows after cleaning: {len(df_filled)}")
print(f"Number of rows removed: {len(df) - len(df_filled)}")

Original number of rows: 785741
Number of rows after cleaning: 785640
Number of rows removed: 101

In [40]:
df_unique = df_filled
df_unique = df_unique.drop_duplicates(subset=['job_title', 'company_name'])
print(f"Original number of rows: {len(df_filled)}")
print(f"Number of rows after cleaning: {len(df_unique)}")
print(f"Number of rows removed: {len(df_filled) - len(df_unique)}")

Original number of rows: 785640
Number of rows after cleaning: 508042
Number of rows removed: 277598